name: CI - Build & Deploy via ArgoCD ApplicationSet

on:
  push:
    branches: [main]

env:
  APP_NAME: argocd-app2
  DOCKER_REPO: faizul56/argocd-app2
  IMAGE_PATH: manifests/deployment.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3

      - name: Install Docker & JQ
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        run: |
          docker build -t $DOCKER_REPO:${{ steps.vars.outputs.sha_short }} .
          docker push $DOCKER_REPO:${{ steps.vars.outputs.sha_short }}

      - name: Clone app repo again for manifest updates
        run: |
          git clone https://x-access-token:${{ secrets.GIT_PAT }}@github.com/faizulkhan56/argocd-app2.git
          cd argocd-app2
          git checkout -B ci-artifacts

      - name: Update image tag in deployment.yaml
        working-directory: argocd-app2
        run: |
          sed -i "s|image: .*|image: $DOCKER_REPO:${{ steps.vars.outputs.sha_short }}|" $IMAGE_PATH

      - name: Commit and push manifest update
        working-directory: argocd-app2
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@github.com"
          git add $IMAGE_PATH
          git commit -m "Update image tag to ${{ steps.vars.outputs.sha_short }}" || echo "No changes to commit"
          git push https://x-access-token:${GIT_PAT}@github.com/faizulkhan56/argocd-app2.git HEAD:ci-artifacts

      - name: Final Message
        run: |
          echo "✅ Build pipeline completed..."
          echo "✅ ArgoCD ApplicationSet will detect changes on ci-artifacts and deploy automatically."

